# Validate this file:
#   curl --data-binary @.codecov.yml https://codecov.io/validate

comment:
  behavior: default

coverage:
  precision: 2
  round: down
  range: "50...70"
  status:
    project:
      default:
        target: 70%
    patch:
      default:
        target: 70%

ignore:
- ".github"
- "hack"
